<!-- List all categories and their second level subcategories -->
<div class="my-block block-list block-categories">

    <div id="block-categories" class="block-title active">
        <img src="<?php echo $this->getSkinUrl('images/minus_pick.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        <strong><span>Categories </span></strong>
    </div>

    <div id="leftnav" class="block-content" style="display:block">
        <?php $helper = $this->helper('catalog/category') ?>
        <?php $categories = $this->getStoreCategories() ?>
        <?php if (count($categories) > 0): ?>
            <ul id="leftnav-tree" class="level0">
                <?php foreach ($categories as $category): ?>
                    <li class="level0<?php if ($this->isCategoryActive($category)): ?> active<?php endif; ?>">
                        <a href="<?php echo $helper->getCategoryUrl($category) ?>"><span><?php echo $this->escapeHtml($category->getName()) ?></span></a>
                        <?php //if ($this->isCategoryActive($category)): ?>
                        <?php $subcategories = $category->getChildren() ?>
                        <?php if (count($subcategories) > 0): ?>
                            <ul id="leftnav-tree-<?php echo $category->getId() ?>" class="level1">
                                <?php foreach ($subcategories as $subcategory): ?>
                                    <li class="level1<?php if ($this->isCategoryActive($subcategory)): ?> active<?php endif; ?>">
                                        <a href="<?php echo $helper->getCategoryUrl($subcategory) ?>"><?php echo $this->escapeHtml(trim($subcategory->getName(), '- ')) ?></a>
                                        <?php $secondLevelSubcategories = $subcategory->getChildren() ?>
                                        <?php if (count($secondLevelSubcategories) > 0): ?>
                                            <ul id="leftnav-tree-<?php echo $subcategory->getId() ?>" class="level2">
                                                <?php foreach ($secondLevelSubcategories as $secondLevelSubcategory): ?>
                                                    <li class="level2<?php if ($this->isCategoryActive($secondLevelSubcategory)): ?> active<?php endif; ?>">
                                                        <a href="<?php echo $helper->getCategoryUrl($secondLevelSubcategory) ?>"><?php echo $this->escapeHtml(trim($secondLevelSubcategory->getName(), '- ')) ?></a>
                                                    </li>
                                                <?php endforeach; ?>
                                            </ul>
                                            <script type="text/javascript">decorateList('leftnav-tree-<?php echo $category->getId() ?>', 'recursive')</script>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                            </ul>
                            <script type="text/javascript">decorateList('leftnav-tree-<?php echo $category->getId() ?>', 'recursive')</script>
                        <?php endif; ?>
                        <?php //endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
            <script type="text/javascript">decorateList('leftnav-tree', 'recursive')</script>
        <?php endif; ?>
    </div>
</div>

<div class="my-current-cat"> 
    <div class="my-current-cat-text">
        <p>Show everything from</p>
    </div>
    <a href="<?php echo $this->__('#') ?>"> <?php echo Mage::getSingleton('catalog/layer')->getCurrentCategory()->getName() ?></a>
</div>

<!-- List all Brands -->


<div class="my-block block-list block-categories">

    <div id="block-categories" class="block-title active">
        <img src="<?php echo $this->getSkinUrl('images/minus_pick.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        <strong><span>Skin Types </span></strong>
        <div class="left-close">
            <a href="<?php echo $this->__('#') ?>"><img src="<?php echo $this->getSkinUrl('images/new_close.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /><?php echo $this->__('Close') ?></a>
        </div>
    </div>
    <div  class="new-block-content" style="display:block">
        <ul class="level1"> 
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Dry Skin') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Oily Skin') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Normal Skin') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Sensitive Skin') ?></label >
            </li>

        </ul>
        <div class="brand-bottom">  
            <p>Do not know your skin type?</p>
            <a href="<?php echo $this->__('#') ?>"><?php echo $this->__('Find out here!') ?></a>
        </div>
    </div>

</div>


<!-- List all Brands -->


<div class="my-block block-list block-categories">

    <div id="block-categories" class="block-title active">
        <img src="<?php echo $this->getSkinUrl('images/minus_pick.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        <strong><span>Brands </span></strong>
        <div class="brand-link">


            <a href="<?php echo $this->__('#') ?>" ><?php echo $this->__('Show all brands') ?></a>
        </div>
    </div>

    <div  class="new-block-content" style="display:block">
        <ul class="level1"> 
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value="" class="checkbox" />
                <label  class="required"><?php echo $this->__('Menscience') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('')  ?>" value="" class="checkbox" />
                <label  class="required"><?php echo $this->__('Nickel') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('The Art of showing') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  checked="" class="checkbox" />
                <label  class="required"><?php echo $this->__('Men-u') ?></label >
               
            </li>
             <li>
               
                 <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  checked="" class="checkbox" />
                <label  class="required"><?php echo $this->__('Boxter of California') ?></label >
            </li>

        </ul>
        
        <div class="brand-link">
            <a href="<?php echo $this->__('#') ?>" ><?php echo $this->__('Show less') ?></a>
        </div>
    </div>

</div>
<!-- List all Brands -->


<div class="my-block block-list block-categories">

    <div id="block-categories" class="block-title active">
        <img src="<?php echo $this->getSkinUrl('images/minus_pick.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        <strong><span>Problem Solution </span></strong>
        <div class="left-close">
            <a href="<?php echo $this->__('#') ?>"><img src="<?php echo $this->getSkinUrl('images/new_close.png') ?>" alt="<?php echo $this->getLogoAlt() ?>" /><?php echo $this->__('Close') ?></a>
        </div>
    </div>
    <div  class="new-block-content" style="display:block">
        <ul class="level1"> 
          
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Razoburn') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Ingrown hairs') ?></label >
            </li>
            <li>
                <input type="checkbox" name="checkbox" title="<?php echo $this->__('') ?>" value=""  class="checkbox" />
                <label  class="required"><?php echo $this->__('Intim shaving irritation') ?></label >
            </li>

        </ul>
      <div class="brand-link">
            <a href="<?php echo $this->__('#') ?>" ><?php echo $this->__('Show more') ?></a>
        </div>
    </div>

</div>


